import type { Metadata } from 'next';
import { Manrope } from 'next/font/google';

import './globals.css';

const manrope = Manrope({
    variable: '--font-manrope',
    subsets: ['latin'],
});

export const metadata: Metadata = {
    title: 'Example Next JS Template',
    description: 'Generated by create next app',
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body className={`${manrope.variable} antialiased`}>
                <main className="flex min-h-screen flex-col items-center justify-center gap-y-16 p-24">
                    {children}
                </main>
            </body>
        </html>
    );
}
