/**
 * Example Root Layout Component
 * 
 * This is a demonstration implementation of the Next.js root layout.
 * 
 * In a real-world application, you should:
 * - Customize metadata (title, description, Open Graph tags)
 * - Add analytics and tracking scripts
 * - Configure fonts based on your brand
 * - Add theme providers (dark mode support)
 * - Include global error boundaries
 * - Add SEO optimization (structured data, favicons)
 * - Configure viewport and mobile settings
 * - Add global providers as needed
 * 
 * Modify this layout based on your project's specific requirements.
 */

import ReactQueryProvider from '@/providers/react-query-provider';
import type { Metadata } from 'next';
import { Manrope } from 'next/font/google';
import { Toaster } from 'sonner';

import './globals.css';

const manrope = Manrope({
    variable: '--font-manrope',
    subsets: ['latin'],
});

export const metadata: Metadata = {
    title: 'Example Next JS Template',
    description: 'Generated by create next app',
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body className={`${manrope.variable} antialiased`}>
                <ReactQueryProvider>
                    <main className="flex min-h-screen flex-col items-center justify-center gap-y-16 p-4 lg:p-8 xl:p-24">
                        {children}
                    </main>
                </ReactQueryProvider>
                <Toaster position="bottom-right" />
            </body>
        </html>
    );
}
